--table 설계
DROP TABLE LIKELIST;
DROP TABLE FREEBOARD;
DROP TABLE INFO;
DROP TABLE MEMBER;
DROP TABLE ADMIN;
DROP TABLE LOCATION;
DROP TABLE THEME;

DROP SEQUENCE FREEBOARD_SEQ;
DROP SEQUENCE INFO_SEQ;
DROP SEQUENCE THEME_SEQ;
DROP SEQUENCE LIKELIST_SEQ;

CREATE SEQUENCE FREEBOARD_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE INFO_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE THEME_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE LIKELIST_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;

CREATE TABLE THEME(
    TNO   NUMBER(6) PRIMARY KEY,
    TNAME VARCHAR2(30) NOT NULL
);
CREATE TABLE LOCATION(
    LNO   NUMBER(6) PRIMARY KEY,
    LNAME VARCHAR2(30) NOT NULL
);
CREATE TABLE ADMIN(
    AID   VARCHAR2(30) PRIMARY KEY,
    APW   VARCHAR2(30) NOT NULL,
    ANAME VARCHAR2(30)
);
CREATE TABLE MEMBER(
    mID      VARCHAR2(30) PRIMARY KEY,
    mPW      VARCHAR2(30) NOT NULL,
    mNAME    VARCHAR2(30) NOT NULL,
    mEMAIL   VARCHAR2(30) UNIQUE, 
    mBIRTH   DATE,
    mADDRESS VARCHAR2(300),
    mRDATE   DATE DEFAULT SYSDATE NOT NULL 
);
CREATE TABLE INFO(
    IID        NUMBER(6)    PRIMARY KEY,
    AID        VARCHAR2(30) REFERENCES ADMIN(AID) NOT NULL,
    ITITLE     VARCHAR2(100) NOT NULL,
    ICONTENT   VARCHAR2(4000),
    LNO        NUMBER(6) REFERENCES LOCATION(LNO),
    TNO        NUMBER(6) REFERENCES THEME(TNO),
    IFILENAME  VARCHAR2(100),
    IFILENAME2 VARCHAR2(100),
    IRDATE     DATE  DEFAULT SYSDATE NOT NULL,
    IHIT       NUMBER(6) NOT NULL,
    IINDENT    NUMBER(6) ,
    IIP        VARCHAR2(30)
);
CREATE TABLE FREEBOARD(
    FID       NUMBER(6)     PRIMARY KEY NOT NULL,
    MID       VARCHAR2(30)  REFERENCES MEMBER(MID) NOT NULL,
    FTITLE    VARCHAR2(100) NOT NULL,
    FCONTENT  VARCHAR2(4000),
    FFILENAME VARCHAR2(100),
    FRDATE    DATE  DEFAULT SYSDATE NOT NULL,
    FHIT      NUMBER(6) DEFAULT 0 NOT NULL,
    FGROUP    NUMBER(6) NOT NULL,
    FSTEP     NUMBER(6) NOT NULL,
    FINDENT   NUMBER(6) NOT NULL,
    FIP       VARCHAR2(30) NOT NULL
);
CREATE TABLE LIKELIST(
    NO  NUMBER(3) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MEMBER(MID) NOT NULL ,
    IID NUMBER(6)  REFERENCES INFO(IID) NOT NULL 
);

COMMIT;

--DUMMYDATA
--THEME
SELECT * FROM THEME;
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '어드벤처'); 
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '까페');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '맛집');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '문화/역사');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '산');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '축제');
--LOCATION
INSERT INTO LOCATION (LNO, LNAME) VALUES (02,'서울');
INSERT INTO LOCATION (LNO, LNAME) VALUES (031,'경기');
INSERT INTO LOCATION (LNO, LNAME) VALUES (032,'인천');
INSERT INTO LOCATION (LNO, LNAME) VALUES (033,'강원');
INSERT INTO LOCATION (LNO, LNAME) VALUES (043,'충북');
INSERT INTO LOCATION (LNO, LNAME) VALUES (041,'충남');
INSERT INTO LOCATION (LNO, LNAME) VALUES (042,'대전');
INSERT INTO LOCATION (LNO, LNAME) VALUES (054,'경북');
INSERT INTO LOCATION (LNO, LNAME) VALUES (055,'경남');
INSERT INTO LOCATION (LNO, LNAME) VALUES (061,'전남');
INSERT INTO LOCATION (LNO, LNAME) VALUES (063,'전북');
INSERT INTO LOCATION (LNO, LNAME) VALUES (062,'광주');
INSERT INTO LOCATION (LNO, LNAME) VALUES (053,'대구');
INSERT INTO LOCATION (LNO, LNAME) VALUES (052,'울산');
INSERT INTO LOCATION (LNO, LNAME) VALUES (051,'부산');
INSERT INTO LOCATION (LNO, LNAME) VALUES (064,'제주');
INSERT INTO LOCATION (LNO, LNAME) VALUES (82,'한국');
--MEMBER
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('gayun','1','김가연','gayun@naver.com','1972/09/09','광주광역시');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('gico','1','지코','gico@naver.com','1992/09/14','서울시');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('go','1','고소영','go@naver.com','1972/10/06','서울시');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('han','1','한지민','han@naver.com','1982/11/05','서울시');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('jang','1','장동건',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('jo','1','조현우',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('kang','1','강동원',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('kim','1','김태희',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('lee','1','이선빈',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('lim','1','임요한',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('park','1','박보검',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('rain','1','비',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('sgy','1','송가연',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('son','1','손흥민',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('song','1','송중기',null,null,null);
SELECT * FROM MEMBER ORDER BY mRDATE DESC;

--ADMIN
SELECT * FROM ADMIN ;
INSERT INTO ADMIN (AID,APW, ANAME) VALUES ('GAN','1','김관리');

--FREEBOARD
SELECT * FROM FREEBOARD ;
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FREEBOARD_SEQ.NEXTVAL, 'son','토트넘','난 공격수', 'a.docx', 
    FREEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');

--INFO
SELECT* FROM INFO;
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','단풍구경가자','서울에서 가장 이쁜 단풍이 피는곳은?','02',5,'단풍.jpg','설악산정원연못.jpg',0,'192.1.1.1');

--LIKELIST
SELECT * FROM LIKELIST; 
INSERT INTO LIKELIST (NO, MID,IID) VALUES (LIKELIST_SEQ.NEXTVAL, 'son',1);

















