--table 설계
DROP TABLE LIKELIST;
DROP TABLE FREEBOARD;
DROP TABLE INFO;
DROP TABLE MEMBER;
DROP TABLE ADMIN;
DROP TABLE LOCATION;
DROP TABLE THEME;

DROP SEQUENCE FREEBOARD_SEQ;
DROP SEQUENCE INFO_SEQ;
DROP SEQUENCE THEME_SEQ;
DROP SEQUENCE LIKELIST_SEQ;
DROP SEQUENCE LOCATION_SEQ;

CREATE SEQUENCE FREEBOARD_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE INFO_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE THEME_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE LIKELIST_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE LOCATION_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;

CREATE TABLE THEME(
    TNO   NUMBER(6) PRIMARY KEY,
    TNAME VARCHAR2(30) NOT NULL
);
CREATE TABLE LOCATION(
    LNO   NUMBER(6) PRIMARY KEY,
    LNAME VARCHAR2(30) NOT NULL
);
CREATE TABLE ADMIN(
    AID   VARCHAR2(30) PRIMARY KEY,
    APW   VARCHAR2(30) NOT NULL,
    ANAME VARCHAR2(30)
);
CREATE TABLE MEMBER(
    mID      VARCHAR2(30) PRIMARY KEY,
    mPW      VARCHAR2(30) NOT NULL,
    mNAME    VARCHAR2(30) NOT NULL,
    mEMAIL   VARCHAR2(30) UNIQUE, 
    mBIRTH   DATE,
    mADDRESS VARCHAR2(300),
    mRDATE   DATE DEFAULT SYSDATE NOT NULL 
);
CREATE TABLE INFO(
    IID        NUMBER(6)    PRIMARY KEY,
    AID        VARCHAR2(30) REFERENCES ADMIN(AID) NOT NULL,
    ITITLE     VARCHAR2(100) NOT NULL,
    ICONTENT   VARCHAR2(4000),
    LNO        NUMBER(6) REFERENCES LOCATION(LNO),
    TNO        NUMBER(6) REFERENCES THEME(TNO),
    IFILENAME  VARCHAR2(100),
    IFILENAME2 VARCHAR2(100),
    IRDATE     DATE  DEFAULT SYSDATE NOT NULL,
    IHIT       NUMBER(6) NOT NULL,
    IINDENT    NUMBER(6) ,
    IIP        VARCHAR2(30)
);
CREATE TABLE FREEBOARD(
    FID       NUMBER(6)     PRIMARY KEY NOT NULL,
    MID       VARCHAR2(30)  REFERENCES MEMBER(MID) NOT NULL,
    FTITLE    VARCHAR2(100) NOT NULL,
    FCONTENT  VARCHAR2(4000),
    FFILENAME VARCHAR2(100),
    FRDATE    DATE  DEFAULT SYSDATE NOT NULL,
    FHIT      NUMBER(6) DEFAULT 0 NOT NULL,
    FGROUP    NUMBER(6) NOT NULL,
    FSTEP     NUMBER(6) NOT NULL,
    FINDENT   NUMBER(6) NOT NULL,
    FIP       VARCHAR2(30) NOT NULL
);
CREATE TABLE LIKELIST(
    NO  NUMBER(3) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MEMBER(MID) NOT NULL ,
    IID NUMBER(6)  REFERENCES INFO(IID) NOT NULL 
);

COMMIT;

--DUMMYDATA
--THEME
SELECT * FROM THEME;
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '어드벤처'); 
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '까페');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '맛집');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '문화/역사');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '산');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '축제');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '바다');
INSERT INTO THEME (TNO, TNAME) VALUES (THEME_SEQ.NEXTVAL, '캠핑');
--LOCATION
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'서울');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'경기');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'인천');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'강원');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'충북');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'충남');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'대전');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'경북');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'경남');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'전남');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'전북');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'광주');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'대구');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'울산');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'부산');
INSERT INTO LOCATION (LNO, LNAME) VALUES (LOCATION_SEQ.NEXTVAL,'제주');
--MEMBER
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('gayun','1','김가연','gayun@naver.com','1972/09/09','광주광역시');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('gico','1','지코','gico@naver.com','1992/09/14','서울시');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('go','1','고소영','go@naver.com','1972/10/06','서울시');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('han','1','한지민','han@naver.com','1982/11/05','서울시');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('jang','1','장동건',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('jo','1','조현우',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('kang','1','강동원',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('kim','1','김태희',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('lee','1','이선빈',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('lim','1','임요한',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('park','1','박보검',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('rain','1','비',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL,  MBIRTH, MADDRESS)
    VALUES ('sgy','1','송가연',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('son','1','손흥민',null,null,null);
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('song','1','송중기',null,null,null);
SELECT * FROM MEMBER ORDER BY mRDATE DESC;

--ADMIN
SELECT * FROM ADMIN ;
INSERT INTO ADMIN (AID,APW, ANAME) VALUES ('GAN','1','김관리');

--FREEBOARD
SELECT * FROM FREEBOARD ;
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FREEBOARD_SEQ.NEXTVAL, 'gayun','수영장','물놀이 좋아', 'beach.jpg', 
    FREEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FREEBOARD_SEQ.NEXTVAL, 'gico','캠핑','캠핑의 꽃은 캠프파이어', 'campfire.jpg', 
    FREEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FREEBOARD_SEQ.NEXTVAL, 'go','가을은 캠핑의 계절','난방텐트 구매했어요', 'camping.jpg', 
    FREEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FREEBOARD_SEQ.NEXTVAL, 'han','맛집투어','곱창 먹으러 가요', 'gopchang.jpg', 
    FREEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FREEBOARD_SEQ.NEXTVAL, 'jang','주말나들이','등산은 아이들과', 'hiking.jpg', 
    FREEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FILEBOARD_SEQ.NEXTVAL, 'jo','단풍구경','설악산으로 단풍구경 다녀왔어요', 'sulak.jpg', 
    FILEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FILEBOARD_SEQ.NEXTVAL, 'kang','단풍구경','설악산으로 단풍구경 다녀왔어요', 'sulak.jpg', 
    FILEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FILEBOARD_SEQ.NEXTVAL, 'kim','제주도 ','해산물먹으러 다녀왔어요', 'seafood.jpg', 
    FILEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
INSERT INTO FREEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FILEBOARD_SEQ.NEXTVAL, 'lee','성수미술관','미술관은 언제나 즐거워', 'artcenter.jpg', 
    FILEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
    
--INFO
SELECT* FROM INFO;
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO, TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','경상남도 합천','가장 이쁜 단풍이 피는곳은? 단풍구경가자',9,5,'danpong.jpg',null,0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO, TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','서울','한강고수부지,불꽃 놀이 치우고 까페가기',1,2,'Seoul.jpg',null,0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','<공지사항>여행위험지역 발생','설악산 낙석주의',4,5,'rock.jpg',NULL,0,1,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','<공지사항>양양해수욕장 폐쇄','상어출몰',4,7,'shack.jpg',NULL,0,1,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','경기도 수원','수원화성에서 역사공부',2,4,'Suwon.jpg',null,0,0,'192.1.1.3');
SELECT* FROM INFO;
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO, TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','경상북도 포항','포항의명물 호미곶',8,7,'Pohang.jpg','Pohang2.jpg',0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO, TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','경상북도 안동','안동에서 역사공부하기',8,4,'Andong.jpg','Andong2.jgp',0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','충청남도 서산','일상속에 역사와 문화가 있는곳',6,4,'seosan.jpg',NULL,0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','제주도','제주올레길에서 바다보자',16,7,'Jeju.jpg',NULL,0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','부산 광안리','광안리 드론쇼 개최',15,6,'Busan.jpg',null,0,0,'192.1.1.3');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','강원도 강릉','강릉해변에서 축제즐기기 ',4,7,'Gangneung.jpg',null,0,0,'192.1.1.3');
delete from info where lno = 1;
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO, TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','강원도 춘천','춘천에서 맛집투어하기',4,3,'Chuncheon.jpg','chi.jpg',0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO, TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','전라남도 여수','케이블카타고 돌산대교 전망보기',10,7,'yeosu.jpg','yeo-su.jpg',0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','대전','대전의 명물 성심당',7,3,'Daejeon.jpg','Bbang.jpg',0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','충청북도 제천','가을 풍경 여행의 1번지, 제천 청풍문화재단지 ',5,4,'dd.jpg',NULL,0,0,'192.1.1.1');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','인천','오이도에서 조개구이 구워먹자',3,3,'Incheon.jpg','jogae.jpg',0,0,'192.1.1.3');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','전라북도 전주','전주에서 한복오감축제 참가하기 ',11,6,'Jeonju.jpg','hanbock.jpg',0,0,'192.1.1.3');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','전라남도 목포','목포바다가 보이는 까페에서 커피한잔 ',10,2,'Mokpo.jpg',null,0,0,'192.1.1.3');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','강원도 영월','스키타러 영월가기 ',4,1,'Yeongwol.jpg',null,0,0,'192.1.1.3');
INSERT INTO INFO (IID, AID, ITITLE, ICONTENT, LNO,TNO, IFILENAME,IFILENAME2 ,IHIT,IINDENT,IIP)
    VALUES (INFO_SEQ.NEXTVAL, 'GAN','경기도 가평','숲속에서 캠핑하기 ',2,8,'Gapyeong.jpg',null,0,0,'192.1.1.3');

delete from info where iid = 3;
delete from freeboard where mid = 'son';
--LIKELIST
SELECT * FROM LIKELIST; 
INSERT INTO LIKELIST (NO, MID,IID) VALUES (LIKELIST_SEQ.NEXTVAL, 'son',1);

commit;
UPDATE FREEBOARD SET FSTEP = FSTEP + 1 WHERE FGROUP=1 AND FSTEP > 0;















